# Identitas unik proyek di dashboard SonarQube
sonar.projectKey=Iswanto25_boilerplate-expressjs
sonar.projectName=Boilerplate ExpressJS
sonar.projectVersion=1.0

# Lokasi sumber kode utama
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Menentukan file TypeScript yang akan dianalisis
sonar.typescript.tsconfigPath=tsconfig.json

# PENTING: Mengecualikan folder agar tidak memperlambat scan
# Ini akan mengabaikan folder scannerwork yang baru saja muncul
sonar.exclusions=**/node_modules/**, **/dist/**, **/.scannerwork/**, **/coverage/**, **/prisma/**

# Lokasi file test (opsional jika Anda punya unit test)
sonar.tests=src
sonar.test.inclusions=**/*.test.ts, **/*.spec.ts

# Tambahkan ini di sonar-project.properties Anda
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.eslint.reportPaths=eslint-report.json

sonar.coverage.exclusions=src/**/*